spring:
  profiles:
    active:
    - dev
    - prod

server:
  servlet:
    context-path: /api
    
---

spring:
  config:
    activate:
      on-profile:
      - dev
  
server:
  port: 8080
  
---

spring:
  config:
    activate:
      on-profile:
      - prod
  
server:
  port: 8081
